### ISSUE TITLE
railway kills its free plan, possible to deploy in Okteto?

### ISSUE THREAD

**Issue by blacktreess** [Andrew-Bekhiet/railway_tailscale_vpn#1]
Hi Bro, your script helps me to deploy tailscale in railway, thanks. but now railway cancel its free plan. Possible to deploy this in Okteto?

**Comment by Andrew-Bekhiet** [comment]
Yeah sure, you can use the scripts to deploy to Okteto, but I have no idea about Okteto and how to deploy to it

**Comment by blacktreess** [comment]
Trying, and thanks for reply.
